import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaClient } from "@prisma/client";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

type FixtureItem = {
  question: string;
  options: string[];
  correctIndex: number;
  difficulty: "E" | "M" | "H";
  tags?: string[];
};

async function main() {
  const prisma = new PrismaClient();
  try {
    const fixturePath = path.resolve(__dirname, "../fixtures/trivia_questions.json");
    const raw = await readFile(fixturePath, "utf-8");
    const items: FixtureItem[] = JSON.parse(raw);

    // Ensure activity exists
    await prisma.activity.upsert({
      where: { key: "quick_trivia" },
      update: {},
      create: { key: "quick_trivia", name: "Quick Trivia", configJson: { rounds: 5, timeLimitMs: 18000, difficulties: ["E","M","H"] } },
    });

    // Insert questions if not present (id is generated by DB, so use a unique composite to prevent dupes)
    let inserted = 0;
    for (const q of items) {
      const existing = await (prisma as any).triviaQuestion.findFirst({
        where: {
          question: q.question,
          correctIndex: q.correctIndex,
        },
      });
      if (existing) continue;
      await (prisma as any).triviaQuestion.create({
        data: {
          question: q.question,
          optionsJson: q.options,
          correctIndex: q.correctIndex,
          difficulty: q.difficulty,
          tagsJson: q.tags ?? [],
        },
      });
      inserted += 1;
    }

    console.log(`Seeded QuickTrivia: inserted ${inserted} new questions (total fixture ${items.length}).`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
